FROM node:16.13.0

WORKDIR /code

ENV PORT 80

COPY pocus_server/pocusJson/package.json /code/package.json

RUN npm install
RUN npm install amqplib
RUN npm install socket.io
RUN npm install socket.io-client
RUN npm install -g nodemon

COPY pocus_server /code

EXPOSE 3000

CMD ["node", "server.js", "pocusMessanger.js"]
